# Turn off CircleCI integration and delete this file once CMake builds are working.

version: 2.1

jobs:
  dummy:
    docker:
      - image: ponylang/ponyc-ci-x86-64-unknown-linux-gnu-builder:20191106
    steps:
      - run: echo Not using CircleCI any more

workflows:
  version: 2.1

  pr-acceptance-tests:
    jobs:
      - dummy:
          context: org-global
          filters:
            branches:
              ignore:
                - master
                - release
